# Generated by Django 3.2.2 on 2022-02-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
